package net.zillions.buffett.client;

import java.util.List;
import net.zillions.buffett.model.TbBookmark;
import net.zillions.buffett.model.TbBookmarkExample;
import org.apache.ibatis.annotations.Param;

public interface TbBookmarkMapper extends Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int countByEx(TbBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int deleteByEx(TbBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int deleteByPk(Integer bookmarkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int insert(TbBookmark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int insertSelective(TbBookmark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	List<TbBookmark> selectByEx(TbBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	TbBookmark findByPk(Integer bookmarkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int updateByExSelective(@Param("record") TbBookmark record, @Param("example") TbBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int updateByEx(@Param("record") TbBookmark record, @Param("example") TbBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int updateByPkSelective(TbBookmark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int updateByPk(TbBookmark record);
}