package net.zillions.buffett.client;

import java.util.List;
import net.zillions.buffett.model.TbLabelBookmark;
import net.zillions.buffett.model.TbLabelBookmarkExample;
import org.apache.ibatis.annotations.Param;

public interface TbLabelBookmarkMapper extends Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int countByEx(TbLabelBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int deleteByEx(TbLabelBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int deleteByPk(@Param("labelId") Integer labelId, @Param("bookmarkId") Integer bookmarkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int insert(TbLabelBookmark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int insertSelective(TbLabelBookmark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	List<TbLabelBookmark> selectByEx(TbLabelBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	TbLabelBookmark findByPk(@Param("labelId") Integer labelId, @Param("bookmarkId") Integer bookmarkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int updateByExSelective(@Param("record") TbLabelBookmark record, @Param("example") TbLabelBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int updateByEx(@Param("record") TbLabelBookmark record, @Param("example") TbLabelBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int updateByPkSelective(TbLabelBookmark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int updateByPk(TbLabelBookmark record);
}