package net.zillions.buffett.client;

import java.util.List;
import net.zillions.buffett.model.TbLabel;
import net.zillions.buffett.model.TbLabelExample;
import org.apache.ibatis.annotations.Param;

public interface TbLabelMapper extends Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int countByEx(TbLabelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int deleteByEx(TbLabelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int deleteByPk(Integer labelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int insert(TbLabel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int insertSelective(TbLabel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	List<TbLabel> selectByEx(TbLabelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	TbLabel findByPk(Integer labelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int updateByExSelective(@Param("record") TbLabel record, @Param("example") TbLabelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int updateByEx(@Param("record") TbLabel record, @Param("example") TbLabelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int updateByPkSelective(TbLabel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	int updateByPk(TbLabel record);
}