package net.zillions.buffett.model;

import java.io.Serializable;
import java.util.Date;

public class TbIndustry implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_industry.industry_id
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Integer industryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_industry.industry_code
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private String industryCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_industry.industry_name
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private String industryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_industry.create_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_industry.created
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Date created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_industry.update_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_industry.updated
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Date updated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_industry.deleted
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Boolean deleted;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_industry
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public TbIndustry(Integer industryId, String industryCode, String industryName, String createUser, Date created,
			String updateUser, Date updated, Boolean deleted) {
		this.industryId = industryId;
		this.industryCode = industryCode;
		this.industryName = industryName;
		this.createUser = createUser;
		this.created = created;
		this.updateUser = updateUser;
		this.updated = updated;
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_industry
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public TbIndustry() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_industry.industry_id
	 * @return  the value of public.tb_industry.industry_id
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Integer getIndustryId() {
		return industryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_industry.industry_id
	 * @param industryId  the value for public.tb_industry.industry_id
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setIndustryId(Integer industryId) {
		this.industryId = industryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_industry.industry_code
	 * @return  the value of public.tb_industry.industry_code
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public String getIndustryCode() {
		return industryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_industry.industry_code
	 * @param industryCode  the value for public.tb_industry.industry_code
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setIndustryCode(String industryCode) {
		this.industryCode = industryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_industry.industry_name
	 * @return  the value of public.tb_industry.industry_name
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public String getIndustryName() {
		return industryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_industry.industry_name
	 * @param industryName  the value for public.tb_industry.industry_name
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setIndustryName(String industryName) {
		this.industryName = industryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_industry.create_user
	 * @return  the value of public.tb_industry.create_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_industry.create_user
	 * @param createUser  the value for public.tb_industry.create_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_industry.created
	 * @return  the value of public.tb_industry.created
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_industry.created
	 * @param created  the value for public.tb_industry.created
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_industry.update_user
	 * @return  the value of public.tb_industry.update_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_industry.update_user
	 * @param updateUser  the value for public.tb_industry.update_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_industry.updated
	 * @return  the value of public.tb_industry.updated
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Date getUpdated() {
		return updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_industry.updated
	 * @param updated  the value for public.tb_industry.updated
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_industry.deleted
	 * @return  the value of public.tb_industry.deleted
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Boolean getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_industry.deleted
	 * @param deleted  the value for public.tb_industry.deleted
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_industry
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", industryId=").append(industryId);
		sb.append(", industryCode=").append(industryCode);
		sb.append(", industryName=").append(industryName);
		sb.append(", createUser=").append(createUser);
		sb.append(", created=").append(created);
		sb.append(", updateUser=").append(updateUser);
		sb.append(", updated=").append(updated);
		sb.append(", deleted=").append(deleted);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 5957978763593662910L;
}