package net.zillions.buffett.model;

import java.io.Serializable;
import java.util.Date;

public class TbLabel implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label.label_id
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Integer labelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label.label_name
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private String labelName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label.use_count
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Integer useCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label.create_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label.created
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Date created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label.update_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label.updated
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Date updated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label.deleted
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Boolean deleted;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public TbLabel(Integer labelId, String labelName, Integer useCount, String createUser, Date created, String updateUser,
			Date updated, Boolean deleted) {
		this.labelId = labelId;
		this.labelName = labelName;
		this.useCount = useCount;
		this.createUser = createUser;
		this.created = created;
		this.updateUser = updateUser;
		this.updated = updated;
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public TbLabel() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label.label_id
	 * @return  the value of public.tb_label.label_id
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Integer getLabelId() {
		return labelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label.label_id
	 * @param labelId  the value for public.tb_label.label_id
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setLabelId(Integer labelId) {
		this.labelId = labelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label.label_name
	 * @return  the value of public.tb_label.label_name
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public String getLabelName() {
		return labelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label.label_name
	 * @param labelName  the value for public.tb_label.label_name
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setLabelName(String labelName) {
		this.labelName = labelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label.use_count
	 * @return  the value of public.tb_label.use_count
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Integer getUseCount() {
		return useCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label.use_count
	 * @param useCount  the value for public.tb_label.use_count
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setUseCount(Integer useCount) {
		this.useCount = useCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label.create_user
	 * @return  the value of public.tb_label.create_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label.create_user
	 * @param createUser  the value for public.tb_label.create_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label.created
	 * @return  the value of public.tb_label.created
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label.created
	 * @param created  the value for public.tb_label.created
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label.update_user
	 * @return  the value of public.tb_label.update_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label.update_user
	 * @param updateUser  the value for public.tb_label.update_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label.updated
	 * @return  the value of public.tb_label.updated
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Date getUpdated() {
		return updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label.updated
	 * @param updated  the value for public.tb_label.updated
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label.deleted
	 * @return  the value of public.tb_label.deleted
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Boolean getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label.deleted
	 * @param deleted  the value for public.tb_label.deleted
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", labelId=").append(labelId);
		sb.append(", labelName=").append(labelName);
		sb.append(", useCount=").append(useCount);
		sb.append(", createUser=").append(createUser);
		sb.append(", created=").append(created);
		sb.append(", updateUser=").append(updateUser);
		sb.append(", updated=").append(updated);
		sb.append(", deleted=").append(deleted);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -5718605184904650803L;
}