package net.zillions.buffett.model;

import java.io.Serializable;
import java.util.Date;

public class TbLabelBookmark implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label_bookmark.label_id
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Integer labelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label_bookmark.bookmark_id
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Integer bookmarkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label_bookmark.create_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label_bookmark.created
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Date created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label_bookmark.update_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label_bookmark.updated
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Date updated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.tb_label_bookmark.deleted
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	private Boolean deleted;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public TbLabelBookmark(Integer labelId, Integer bookmarkId, String createUser, Date created, String updateUser, Date updated,
			Boolean deleted) {
		this.labelId = labelId;
		this.bookmarkId = bookmarkId;
		this.createUser = createUser;
		this.created = created;
		this.updateUser = updateUser;
		this.updated = updated;
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public TbLabelBookmark() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label_bookmark.label_id
	 * @return  the value of public.tb_label_bookmark.label_id
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Integer getLabelId() {
		return labelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label_bookmark.label_id
	 * @param labelId  the value for public.tb_label_bookmark.label_id
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setLabelId(Integer labelId) {
		this.labelId = labelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label_bookmark.bookmark_id
	 * @return  the value of public.tb_label_bookmark.bookmark_id
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Integer getBookmarkId() {
		return bookmarkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label_bookmark.bookmark_id
	 * @param bookmarkId  the value for public.tb_label_bookmark.bookmark_id
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setBookmarkId(Integer bookmarkId) {
		this.bookmarkId = bookmarkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label_bookmark.create_user
	 * @return  the value of public.tb_label_bookmark.create_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label_bookmark.create_user
	 * @param createUser  the value for public.tb_label_bookmark.create_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label_bookmark.created
	 * @return  the value of public.tb_label_bookmark.created
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label_bookmark.created
	 * @param created  the value for public.tb_label_bookmark.created
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label_bookmark.update_user
	 * @return  the value of public.tb_label_bookmark.update_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label_bookmark.update_user
	 * @param updateUser  the value for public.tb_label_bookmark.update_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label_bookmark.updated
	 * @return  the value of public.tb_label_bookmark.updated
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Date getUpdated() {
		return updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label_bookmark.updated
	 * @param updated  the value for public.tb_label_bookmark.updated
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.tb_label_bookmark.deleted
	 * @return  the value of public.tb_label_bookmark.deleted
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Boolean getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.tb_label_bookmark.deleted
	 * @param deleted  the value for public.tb_label_bookmark.deleted
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_label_bookmark
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", labelId=").append(labelId);
		sb.append(", bookmarkId=").append(bookmarkId);
		sb.append(", createUser=").append(createUser);
		sb.append(", created=").append(created);
		sb.append(", updateUser=").append(updateUser);
		sb.append(", updated=").append(updated);
		sb.append(", deleted=").append(deleted);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 8582762330552387142L;
}