package net.zillions.buffett.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbStockExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public TbStockExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andStockIdIsNull() {
			addCriterion("stock_id is null");
			return (Criteria) this;
		}

		public Criteria andStockIdIsNotNull() {
			addCriterion("stock_id is not null");
			return (Criteria) this;
		}

		public Criteria andStockIdEqualTo(Integer value) {
			addCriterion("stock_id =", value, "stockId");
			return (Criteria) this;
		}

		public Criteria andStockIdNotEqualTo(Integer value) {
			addCriterion("stock_id <>", value, "stockId");
			return (Criteria) this;
		}

		public Criteria andStockIdGreaterThan(Integer value) {
			addCriterion("stock_id >", value, "stockId");
			return (Criteria) this;
		}

		public Criteria andStockIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("stock_id >=", value, "stockId");
			return (Criteria) this;
		}

		public Criteria andStockIdLessThan(Integer value) {
			addCriterion("stock_id <", value, "stockId");
			return (Criteria) this;
		}

		public Criteria andStockIdLessThanOrEqualTo(Integer value) {
			addCriterion("stock_id <=", value, "stockId");
			return (Criteria) this;
		}

		public Criteria andStockIdIn(List<Integer> values) {
			addCriterion("stock_id in", values, "stockId");
			return (Criteria) this;
		}

		public Criteria andStockIdNotIn(List<Integer> values) {
			addCriterion("stock_id not in", values, "stockId");
			return (Criteria) this;
		}

		public Criteria andStockIdBetween(Integer value1, Integer value2) {
			addCriterion("stock_id between", value1, value2, "stockId");
			return (Criteria) this;
		}

		public Criteria andStockIdNotBetween(Integer value1, Integer value2) {
			addCriterion("stock_id not between", value1, value2, "stockId");
			return (Criteria) this;
		}

		public Criteria andStockCodeIsNull() {
			addCriterion("stock_code is null");
			return (Criteria) this;
		}

		public Criteria andStockCodeIsNotNull() {
			addCriterion("stock_code is not null");
			return (Criteria) this;
		}

		public Criteria andStockCodeEqualTo(String value) {
			addCriterion("stock_code =", value, "stockCode");
			return (Criteria) this;
		}

		public Criteria andStockCodeNotEqualTo(String value) {
			addCriterion("stock_code <>", value, "stockCode");
			return (Criteria) this;
		}

		public Criteria andStockCodeGreaterThan(String value) {
			addCriterion("stock_code >", value, "stockCode");
			return (Criteria) this;
		}

		public Criteria andStockCodeGreaterThanOrEqualTo(String value) {
			addCriterion("stock_code >=", value, "stockCode");
			return (Criteria) this;
		}

		public Criteria andStockCodeLessThan(String value) {
			addCriterion("stock_code <", value, "stockCode");
			return (Criteria) this;
		}

		public Criteria andStockCodeLessThanOrEqualTo(String value) {
			addCriterion("stock_code <=", value, "stockCode");
			return (Criteria) this;
		}

		public Criteria andStockCodeLike(String value) {
			addCriterion("stock_code like", value, "stockCode");
			return (Criteria) this;
		}

		public Criteria andStockCodeNotLike(String value) {
			addCriterion("stock_code not like", value, "stockCode");
			return (Criteria) this;
		}

		public Criteria andStockCodeIn(List<String> values) {
			addCriterion("stock_code in", values, "stockCode");
			return (Criteria) this;
		}

		public Criteria andStockCodeNotIn(List<String> values) {
			addCriterion("stock_code not in", values, "stockCode");
			return (Criteria) this;
		}

		public Criteria andStockCodeBetween(String value1, String value2) {
			addCriterion("stock_code between", value1, value2, "stockCode");
			return (Criteria) this;
		}

		public Criteria andStockCodeNotBetween(String value1, String value2) {
			addCriterion("stock_code not between", value1, value2, "stockCode");
			return (Criteria) this;
		}

		public Criteria andStockNameIsNull() {
			addCriterion("stock_name is null");
			return (Criteria) this;
		}

		public Criteria andStockNameIsNotNull() {
			addCriterion("stock_name is not null");
			return (Criteria) this;
		}

		public Criteria andStockNameEqualTo(String value) {
			addCriterion("stock_name =", value, "stockName");
			return (Criteria) this;
		}

		public Criteria andStockNameNotEqualTo(String value) {
			addCriterion("stock_name <>", value, "stockName");
			return (Criteria) this;
		}

		public Criteria andStockNameGreaterThan(String value) {
			addCriterion("stock_name >", value, "stockName");
			return (Criteria) this;
		}

		public Criteria andStockNameGreaterThanOrEqualTo(String value) {
			addCriterion("stock_name >=", value, "stockName");
			return (Criteria) this;
		}

		public Criteria andStockNameLessThan(String value) {
			addCriterion("stock_name <", value, "stockName");
			return (Criteria) this;
		}

		public Criteria andStockNameLessThanOrEqualTo(String value) {
			addCriterion("stock_name <=", value, "stockName");
			return (Criteria) this;
		}

		public Criteria andStockNameLike(String value) {
			addCriterion("stock_name like", value, "stockName");
			return (Criteria) this;
		}

		public Criteria andStockNameNotLike(String value) {
			addCriterion("stock_name not like", value, "stockName");
			return (Criteria) this;
		}

		public Criteria andStockNameIn(List<String> values) {
			addCriterion("stock_name in", values, "stockName");
			return (Criteria) this;
		}

		public Criteria andStockNameNotIn(List<String> values) {
			addCriterion("stock_name not in", values, "stockName");
			return (Criteria) this;
		}

		public Criteria andStockNameBetween(String value1, String value2) {
			addCriterion("stock_name between", value1, value2, "stockName");
			return (Criteria) this;
		}

		public Criteria andStockNameNotBetween(String value1, String value2) {
			addCriterion("stock_name not between", value1, value2, "stockName");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeIsNull() {
			addCriterion("industry_code is null");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeIsNotNull() {
			addCriterion("industry_code is not null");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeEqualTo(String value) {
			addCriterion("industry_code =", value, "industryCode");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeNotEqualTo(String value) {
			addCriterion("industry_code <>", value, "industryCode");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeGreaterThan(String value) {
			addCriterion("industry_code >", value, "industryCode");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeGreaterThanOrEqualTo(String value) {
			addCriterion("industry_code >=", value, "industryCode");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeLessThan(String value) {
			addCriterion("industry_code <", value, "industryCode");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeLessThanOrEqualTo(String value) {
			addCriterion("industry_code <=", value, "industryCode");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeLike(String value) {
			addCriterion("industry_code like", value, "industryCode");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeNotLike(String value) {
			addCriterion("industry_code not like", value, "industryCode");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeIn(List<String> values) {
			addCriterion("industry_code in", values, "industryCode");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeNotIn(List<String> values) {
			addCriterion("industry_code not in", values, "industryCode");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeBetween(String value1, String value2) {
			addCriterion("industry_code between", value1, value2, "industryCode");
			return (Criteria) this;
		}

		public Criteria andIndustryCodeNotBetween(String value1, String value2) {
			addCriterion("industry_code not between", value1, value2, "industryCode");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("create_user is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("create_user is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("create_user =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("create_user <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("create_user >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("create_user >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("create_user <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("create_user <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("create_user like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("create_user not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("create_user in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("create_user not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("create_user between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("create_user not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreatedIsNull() {
			addCriterion("created is null");
			return (Criteria) this;
		}

		public Criteria andCreatedIsNotNull() {
			addCriterion("created is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedEqualTo(Date value) {
			addCriterion("created =", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotEqualTo(Date value) {
			addCriterion("created <>", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedGreaterThan(Date value) {
			addCriterion("created >", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
			addCriterion("created >=", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedLessThan(Date value) {
			addCriterion("created <", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedLessThanOrEqualTo(Date value) {
			addCriterion("created <=", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedIn(List<Date> values) {
			addCriterion("created in", values, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotIn(List<Date> values) {
			addCriterion("created not in", values, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedBetween(Date value1, Date value2) {
			addCriterion("created between", value1, value2, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotBetween(Date value1, Date value2) {
			addCriterion("created not between", value1, value2, "created");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("update_user is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("update_user is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(String value) {
			addCriterion("update_user =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(String value) {
			addCriterion("update_user <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(String value) {
			addCriterion("update_user >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
			addCriterion("update_user >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(String value) {
			addCriterion("update_user <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(String value) {
			addCriterion("update_user <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLike(String value) {
			addCriterion("update_user like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotLike(String value) {
			addCriterion("update_user not like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<String> values) {
			addCriterion("update_user in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<String> values) {
			addCriterion("update_user not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(String value1, String value2) {
			addCriterion("update_user between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(String value1, String value2) {
			addCriterion("update_user not between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdatedIsNull() {
			addCriterion("updated is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedIsNotNull() {
			addCriterion("updated is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedEqualTo(Date value) {
			addCriterion("updated =", value, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedNotEqualTo(Date value) {
			addCriterion("updated <>", value, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedGreaterThan(Date value) {
			addCriterion("updated >", value, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedGreaterThanOrEqualTo(Date value) {
			addCriterion("updated >=", value, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedLessThan(Date value) {
			addCriterion("updated <", value, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedLessThanOrEqualTo(Date value) {
			addCriterion("updated <=", value, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedIn(List<Date> values) {
			addCriterion("updated in", values, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedNotIn(List<Date> values) {
			addCriterion("updated not in", values, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedBetween(Date value1, Date value2) {
			addCriterion("updated between", value1, value2, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedNotBetween(Date value1, Date value2) {
			addCriterion("updated not between", value1, value2, "updated");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNull() {
			addCriterion("deleted is null");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNotNull() {
			addCriterion("deleted is not null");
			return (Criteria) this;
		}

		public Criteria andDeletedEqualTo(Boolean value) {
			addCriterion("deleted =", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotEqualTo(Boolean value) {
			addCriterion("deleted <>", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThan(Boolean value) {
			addCriterion("deleted >", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("deleted >=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThan(Boolean value) {
			addCriterion("deleted <", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
			addCriterion("deleted <=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedIn(List<Boolean> values) {
			addCriterion("deleted in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotIn(List<Boolean> values) {
			addCriterion("deleted not in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
			addCriterion("deleted between", value1, value2, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("deleted not between", value1, value2, "deleted");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_stock
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tb_stock
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 23 17:54:59 JST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}