package net.zillions.buffett.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbUserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public TbUserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andNameFirstIsNull() {
			addCriterion("name_first is null");
			return (Criteria) this;
		}

		public Criteria andNameFirstIsNotNull() {
			addCriterion("name_first is not null");
			return (Criteria) this;
		}

		public Criteria andNameFirstEqualTo(String value) {
			addCriterion("name_first =", value, "nameFirst");
			return (Criteria) this;
		}

		public Criteria andNameFirstNotEqualTo(String value) {
			addCriterion("name_first <>", value, "nameFirst");
			return (Criteria) this;
		}

		public Criteria andNameFirstGreaterThan(String value) {
			addCriterion("name_first >", value, "nameFirst");
			return (Criteria) this;
		}

		public Criteria andNameFirstGreaterThanOrEqualTo(String value) {
			addCriterion("name_first >=", value, "nameFirst");
			return (Criteria) this;
		}

		public Criteria andNameFirstLessThan(String value) {
			addCriterion("name_first <", value, "nameFirst");
			return (Criteria) this;
		}

		public Criteria andNameFirstLessThanOrEqualTo(String value) {
			addCriterion("name_first <=", value, "nameFirst");
			return (Criteria) this;
		}

		public Criteria andNameFirstLike(String value) {
			addCriterion("name_first like", value, "nameFirst");
			return (Criteria) this;
		}

		public Criteria andNameFirstNotLike(String value) {
			addCriterion("name_first not like", value, "nameFirst");
			return (Criteria) this;
		}

		public Criteria andNameFirstIn(List<String> values) {
			addCriterion("name_first in", values, "nameFirst");
			return (Criteria) this;
		}

		public Criteria andNameFirstNotIn(List<String> values) {
			addCriterion("name_first not in", values, "nameFirst");
			return (Criteria) this;
		}

		public Criteria andNameFirstBetween(String value1, String value2) {
			addCriterion("name_first between", value1, value2, "nameFirst");
			return (Criteria) this;
		}

		public Criteria andNameFirstNotBetween(String value1, String value2) {
			addCriterion("name_first not between", value1, value2, "nameFirst");
			return (Criteria) this;
		}

		public Criteria andNameMiddleIsNull() {
			addCriterion("name_middle is null");
			return (Criteria) this;
		}

		public Criteria andNameMiddleIsNotNull() {
			addCriterion("name_middle is not null");
			return (Criteria) this;
		}

		public Criteria andNameMiddleEqualTo(String value) {
			addCriterion("name_middle =", value, "nameMiddle");
			return (Criteria) this;
		}

		public Criteria andNameMiddleNotEqualTo(String value) {
			addCriterion("name_middle <>", value, "nameMiddle");
			return (Criteria) this;
		}

		public Criteria andNameMiddleGreaterThan(String value) {
			addCriterion("name_middle >", value, "nameMiddle");
			return (Criteria) this;
		}

		public Criteria andNameMiddleGreaterThanOrEqualTo(String value) {
			addCriterion("name_middle >=", value, "nameMiddle");
			return (Criteria) this;
		}

		public Criteria andNameMiddleLessThan(String value) {
			addCriterion("name_middle <", value, "nameMiddle");
			return (Criteria) this;
		}

		public Criteria andNameMiddleLessThanOrEqualTo(String value) {
			addCriterion("name_middle <=", value, "nameMiddle");
			return (Criteria) this;
		}

		public Criteria andNameMiddleLike(String value) {
			addCriterion("name_middle like", value, "nameMiddle");
			return (Criteria) this;
		}

		public Criteria andNameMiddleNotLike(String value) {
			addCriterion("name_middle not like", value, "nameMiddle");
			return (Criteria) this;
		}

		public Criteria andNameMiddleIn(List<String> values) {
			addCriterion("name_middle in", values, "nameMiddle");
			return (Criteria) this;
		}

		public Criteria andNameMiddleNotIn(List<String> values) {
			addCriterion("name_middle not in", values, "nameMiddle");
			return (Criteria) this;
		}

		public Criteria andNameMiddleBetween(String value1, String value2) {
			addCriterion("name_middle between", value1, value2, "nameMiddle");
			return (Criteria) this;
		}

		public Criteria andNameMiddleNotBetween(String value1, String value2) {
			addCriterion("name_middle not between", value1, value2, "nameMiddle");
			return (Criteria) this;
		}

		public Criteria andNameFamilyIsNull() {
			addCriterion("name_family is null");
			return (Criteria) this;
		}

		public Criteria andNameFamilyIsNotNull() {
			addCriterion("name_family is not null");
			return (Criteria) this;
		}

		public Criteria andNameFamilyEqualTo(String value) {
			addCriterion("name_family =", value, "nameFamily");
			return (Criteria) this;
		}

		public Criteria andNameFamilyNotEqualTo(String value) {
			addCriterion("name_family <>", value, "nameFamily");
			return (Criteria) this;
		}

		public Criteria andNameFamilyGreaterThan(String value) {
			addCriterion("name_family >", value, "nameFamily");
			return (Criteria) this;
		}

		public Criteria andNameFamilyGreaterThanOrEqualTo(String value) {
			addCriterion("name_family >=", value, "nameFamily");
			return (Criteria) this;
		}

		public Criteria andNameFamilyLessThan(String value) {
			addCriterion("name_family <", value, "nameFamily");
			return (Criteria) this;
		}

		public Criteria andNameFamilyLessThanOrEqualTo(String value) {
			addCriterion("name_family <=", value, "nameFamily");
			return (Criteria) this;
		}

		public Criteria andNameFamilyLike(String value) {
			addCriterion("name_family like", value, "nameFamily");
			return (Criteria) this;
		}

		public Criteria andNameFamilyNotLike(String value) {
			addCriterion("name_family not like", value, "nameFamily");
			return (Criteria) this;
		}

		public Criteria andNameFamilyIn(List<String> values) {
			addCriterion("name_family in", values, "nameFamily");
			return (Criteria) this;
		}

		public Criteria andNameFamilyNotIn(List<String> values) {
			addCriterion("name_family not in", values, "nameFamily");
			return (Criteria) this;
		}

		public Criteria andNameFamilyBetween(String value1, String value2) {
			addCriterion("name_family between", value1, value2, "nameFamily");
			return (Criteria) this;
		}

		public Criteria andNameFamilyNotBetween(String value1, String value2) {
			addCriterion("name_family not between", value1, value2, "nameFamily");
			return (Criteria) this;
		}

		public Criteria andMailAddressIsNull() {
			addCriterion("mail_address is null");
			return (Criteria) this;
		}

		public Criteria andMailAddressIsNotNull() {
			addCriterion("mail_address is not null");
			return (Criteria) this;
		}

		public Criteria andMailAddressEqualTo(String value) {
			addCriterion("mail_address =", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotEqualTo(String value) {
			addCriterion("mail_address <>", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressGreaterThan(String value) {
			addCriterion("mail_address >", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressGreaterThanOrEqualTo(String value) {
			addCriterion("mail_address >=", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressLessThan(String value) {
			addCriterion("mail_address <", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressLessThanOrEqualTo(String value) {
			addCriterion("mail_address <=", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressLike(String value) {
			addCriterion("mail_address like", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotLike(String value) {
			addCriterion("mail_address not like", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressIn(List<String> values) {
			addCriterion("mail_address in", values, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotIn(List<String> values) {
			addCriterion("mail_address not in", values, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressBetween(String value1, String value2) {
			addCriterion("mail_address between", value1, value2, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotBetween(String value1, String value2) {
			addCriterion("mail_address not between", value1, value2, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("create_user is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("create_user is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("create_user =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("create_user <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("create_user >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("create_user >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("create_user <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("create_user <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("create_user like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("create_user not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("create_user in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("create_user not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("create_user between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("create_user not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreatedIsNull() {
			addCriterion("created is null");
			return (Criteria) this;
		}

		public Criteria andCreatedIsNotNull() {
			addCriterion("created is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedEqualTo(Date value) {
			addCriterion("created =", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotEqualTo(Date value) {
			addCriterion("created <>", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedGreaterThan(Date value) {
			addCriterion("created >", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
			addCriterion("created >=", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedLessThan(Date value) {
			addCriterion("created <", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedLessThanOrEqualTo(Date value) {
			addCriterion("created <=", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedIn(List<Date> values) {
			addCriterion("created in", values, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotIn(List<Date> values) {
			addCriterion("created not in", values, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedBetween(Date value1, Date value2) {
			addCriterion("created between", value1, value2, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotBetween(Date value1, Date value2) {
			addCriterion("created not between", value1, value2, "created");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("update_user is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("update_user is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(String value) {
			addCriterion("update_user =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(String value) {
			addCriterion("update_user <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(String value) {
			addCriterion("update_user >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
			addCriterion("update_user >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(String value) {
			addCriterion("update_user <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(String value) {
			addCriterion("update_user <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLike(String value) {
			addCriterion("update_user like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotLike(String value) {
			addCriterion("update_user not like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<String> values) {
			addCriterion("update_user in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<String> values) {
			addCriterion("update_user not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(String value1, String value2) {
			addCriterion("update_user between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(String value1, String value2) {
			addCriterion("update_user not between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdatedIsNull() {
			addCriterion("updated is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedIsNotNull() {
			addCriterion("updated is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedEqualTo(Date value) {
			addCriterion("updated =", value, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedNotEqualTo(Date value) {
			addCriterion("updated <>", value, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedGreaterThan(Date value) {
			addCriterion("updated >", value, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedGreaterThanOrEqualTo(Date value) {
			addCriterion("updated >=", value, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedLessThan(Date value) {
			addCriterion("updated <", value, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedLessThanOrEqualTo(Date value) {
			addCriterion("updated <=", value, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedIn(List<Date> values) {
			addCriterion("updated in", values, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedNotIn(List<Date> values) {
			addCriterion("updated not in", values, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedBetween(Date value1, Date value2) {
			addCriterion("updated between", value1, value2, "updated");
			return (Criteria) this;
		}

		public Criteria andUpdatedNotBetween(Date value1, Date value2) {
			addCriterion("updated not between", value1, value2, "updated");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNull() {
			addCriterion("deleted is null");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNotNull() {
			addCriterion("deleted is not null");
			return (Criteria) this;
		}

		public Criteria andDeletedEqualTo(Boolean value) {
			addCriterion("deleted =", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotEqualTo(Boolean value) {
			addCriterion("deleted <>", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThan(Boolean value) {
			addCriterion("deleted >", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("deleted >=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThan(Boolean value) {
			addCriterion("deleted <", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
			addCriterion("deleted <=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedIn(List<Boolean> values) {
			addCriterion("deleted in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotIn(List<Boolean> values) {
			addCriterion("deleted not in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
			addCriterion("deleted between", value1, value2, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("deleted not between", value1, value2, "deleted");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.tb_user
	 * @mbggenerated  Tue Jun 24 18:59:38 JST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.tb_user
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 23 17:54:59 JST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}